### ISSUE TITLE
NO access to credit

### ISSUE THREAD

**Issue by awsandy** [aws-samples/amazon-sagemaker-lakeformation-datamesh#1]
Hi,

The sample data "credit_card.csv" used in the producers stack is not publicly available - and so it produces a 403 when the Lambda runs

From the cloudwatch log for the Custom::LoadDataBucket.  Lambda:

Error in Custom Resource An error occurred (403) when calling the HeadObject operation: Forbidden 

You can see the same thing on the command line:

aws s3 cp s3://database-for-sharing-data/blog-ml-datamesh/credit_card.csv .
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by awsandy** [comment]
Looks like the CF template here is not the same as in the blog post (the blog post one works)

**Comment by bpatoul** [comment]
Hello, 

Thank you for your feedback. I have updated the cloud formation templates from the repository to the correct ones.

Let me know if you have any further issues. 

ben
